---
title: "Deliberation Costs"
mainfont: SF Pro Text Light
mainfontoptions: BoldFont = SF Pro Text Semibold
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    includes:
        in_header: rmd-title-fix.tex
fontsize: 11pt
indent: true
bibliography: "../oldpapers/CollBib.bib"
biblio-style: philreview
geometry: "left=1.95in,right=1.95in,top=1.78in,bottom=1.78in"
author: Brian Weatherson
date: \today
---

# The Puzzle

Our hero, let's call him Hercules, faces a choice between three options. All of them depend on whether a particular fair coin landed heads or tails. Let $H$ be the proposition that it lands heads, and $T = \neg H$ be that it lands tails. Hercules knows the coin was fair and was tossed, but has no more relevant information. Two of Hercules's options depend on whether a particular proposition $p$ is true. I'll say in a bit what $p$ is, but first let's set up the puzzle.

- Option A returns 60 if $H$, and 40 if $T$, so it has an expected return of 50.
- Option B returns 1 more than A if $p$ is true, and 10 less than $A$ if $p$ is false.
- Option C returns 1 more than A if $p$ is false, and 10 less than $A$ if $p$ is true.

What's $p$ then? It is the proposition that the following equation has a solution such that $x < 5$.

$$
x^2 - 18x + 60 = 0
$$

Hercules knows how to solve equations like this. In fact, as we'll get to soon, he knows two different ways to solve them. But he can't solve them instantly; it will take a little time and attention. And time and attention are valuable commodities for Hercules, because there are arrows flying around. He's Hercules, so there isn't much to worry about, but still he puts the cost of spending the time to solve this equation as 5.

Now what is it rational for Hercules to do? What is it that he should, rationally speaking, do? In the literature there are two answers to this, though one of them is overwhelmingly more popular than the other.

One answer is that the rational thing to do is B. It strictly dominates the other options - in all possible worlds it has a higher return than the other options. And Hercules is in a position to know this. He knows the algorithm for solving quadratic equations, he just has to apply it. Now it's true that Hercules is not in any position to do apply the algorithm right away. But, says this answer, this is a rational failing on Hercules's part. If he were rational, he would not have this limitation. And the rational thing to do is what he would do were he rational, i.e., were he devoid of rational limitations like this. In that case, he would see that option B is strictly dominant, and would choose it. That answer, or something very much like it, is basically orthodoxy among decision theorists.

Another answer is that the rational thing to do is A. Hercules knows that solving the equation has cost 5, and benefit 1. So it fails the cost-benefit test, and should not be done. And if Hercules does not solve the equation, choosing either B or C involves simply guessing in a scenario where correct guesses win much less than incorrect guesses lose. So he shouldn't guess - he should just choose A. The key idea behind this idea is that Hercules should take **deliberation costs** seriously, and that option A is the rational choice net of deliberation costs. This answer is what I'm going to defend. And while I am a long way from the first person to defend it, it is very much a minority position.

This paper has three primary aims.

1. To show how taking deliberation costs seriously helps us square some well known facts about choice in everyday situation with expected utility theory. In particular, I'll argue that it is only by taking deliberation costs seriously that we can explain the fact that when faced with a choice between almost indistinguishable option - such as choosing a can from a supermarket shelf - there are a lot of rationally permissible choices.
2. To argue that it is implausible to make rationality sensitive to informational limitations but not to deliberational limitations. A lot of this paper follows the arguments in favour of taking deliberation costs seriously that John @Conlisk1996 developed; this part follows his work particularly closely.
3. To respond to the most common objection to taking deliberation costs seriously - that it leads to a vicious regress.

To see point 2, imagine that Hercules has six more options, $D_1$ to $D_6$. A die has been cast, and it came up $i$, and option $D_i$ returns 120, while the other five options return 0. Hercules again doesn't know how the die landed, but he does know it was fair. The expected return of each $D_i$ is 20, so everyone agrees he shouldn't select each of them. But of course if he were cognitively perfect, if he were God and not merely a god, he would know that one of these options were optimal and select it. The orthodox approach to decision theory says that we should not abstract or idealise away from Hercules's inability to know how the die landed, and instead take his ignorance as it is. Just like the orthodox theory says we should take as fixed Hercules's inability to see how the physical world is, I think we should sometimes take as fixed his inability to see how the mathematical world is.

To see point 3, it helps instead to take an option away. In particular, we'll take away option A. Now Hercules really has to solve the equation. But Hercules still has options. As you may remember from school-time mathematics, there are a couple of ways to attack problems like this. You can apply the familiar quadratic formula

$$
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

Or you can just starting randomly selecting pairs of numbers $y$ and $z$ and just see whether $y + z = -b$ while $yz = c$. If you find such a pair, then you'll have a factorisation of the quadratic equation, since its left-hand side will be equal to $(x - y)(x-z)$, and it is obvious what the roots of this are. At least sometimes, this search method is more efficient than working out the quadratic formula in one's head. 

Hercules now has to decide whether to start working through the formula or semi-randomly searching for factors of the left-hand side. How does the view that Hercules should take deliberation costs seriously say he should make this choice? In particular, is the rational thing to do here a function of the actual costs of applying one or other method, or of the expected costs of applying one or other method? Either answer appears to lead to costs. If one says it is the actual costs, then the resulting view is somewhat hard to motivate. One ends up saying that rationality does not require maximising expected utility, on the grounds that the chooser need not know what choice has that feature, but does require maximising efficiency of choice procedure, even though the chooser may not know what maximises efficiency. If one says it is the expected costs, then we are off on the run of a nasty regress. After all, Hercules might find it just as hard to calculate, or even estimate, the expected costs of deliberating one way or the other as to choose one way or the other.

- Set out point 2 using D1-D6 options
- Set out point 3 using two possible methods
- Get going

- History section




# Summary

* There are several reasons to include deliberation cost in our model of rational choice - these include getting the right result in supermarket choice cases, avoiding regret, and avoiding painful computations.
* Orthodoxy is that doing this will lead to infinite regress.
* I think it won't lead to regress.
* If I have time (I probably won't) I'll note how this relates to my work on knowledge.

# An Example {#frankielee}

Let's start with an example from a great thinker. It will require a little exegesis, but that's not unusual when using classic texts.

> | Well Frankie Lee and Judas Priest
| They were the best of friends
| So when Frankie Lee needed money one day
| Judas quickly pulled out a roll of tens
| And placed them on the footstool
| Just above the potted plain
| Saying "Take your pick, Frankie boy,
| My loss will be your gain." 
|           ("The Ballad of Frankie Lee and Judas Priest", 1968. 
|            Lyrics from Bob @Dylan2016 225)

On a common reading of this, Judas Priest isn't just asking Frankie Lee how much money he wants to take, but which invididual notes. Let's simplify, and say that it is common ground that Frankie should only take $10, so the choice Frankie Lee has is which of the individual notes he will take. This will be enough to set up the puzzle.

Assume something else that isn't in the text, but which isn't an implausible addition to the story. The world Frankie Lee and Judas Priest live in is not completely free of counterfeit notes. And it would be bad for Frankie Lee to take a counterfeit note. It won't matter just how common these notes are, or how bad it would be. But our puzzle will be most vivid if each of these are relatively small quantities. So there aren't that many counterfeit notes in circulation, and the (expected) disutility to Frankie Lee of having one of them is not great. There is some chance that he will get in trouble, but the chance isn't high, and the trouble isn't any worse than he's suffered before. Still, other things exactly equal, Frankie Lee would prefer a genuine note to a counterfeit one.

Now for some terminology to help us state the problem Frankie Lee is in. Assume there are $k$ notes on the footstool. Call them $n_1, \dots, n_k$. Let $c_i$ be the proposition that note $n_i$ is counterfeit, and its negation $g_i$ be that it is genuine. Let $g$, without a subscript, be the conjunction $g_1 \wedge \dots \wedge g_n$; i.e., the proposition that all the notes are genuine. Let $t_i$ be the act of taking note $n_i$. Let $U$ be Frankie Lee's utility function, and $Cr$ his credence function.

In our first version of the example, we'll make two more assumptions. Apart from the issue of whether the note is real or counterfeit, Frankie Lee is indifferent between the notes, so for some $h, l$, $U(t_i | g_i) = h$ and $U(t_i | c_i) = l$ for all $i$, with of course $h > l$. If we add an extra assumption that Frankie Lee thinks the probability that each of the notes is genuine is the same, we get the intuitive result back that he is indifferent between the banknotes.

But is that really a plausible move? Here is one way to start worrying about it. Change the example so that the country Frankie Lee and Judas Priest live in is very slowly modernising its currency. It is getting rid of old fashioned, and somewhat easy to counterfeit, paper money, and joining the civilised countries that use plastic money. Moreover, plastic bank notes are, for all intents and purposes, impossible to counterfeit. (At least, no one has yet figured out how to do it, and Frankie Lee knows this.) 

Some of the notes Judas Priest offers are the new plastic notes, and some are the old paper notes. Now it seems clear that Frankie Lee should take one of the new notes, and not merely on aesthetic grounds. Rather, the fact that the plastic notes are less likely to be counterfeit is a reason to prefer to take them. And this is true no matter how unlikely it is that the paper notes are counterfeit, as long as this likelihood is non-zero.

But now go back to the base case, where all the money is paper. A small change in probability of being counterfeit seems to be enough to give Frankie Lee a reason to prefer some of them to the others. Indeed, the only way for him to be indifferent between the notes is if the probability of any one being counterfeit is exactly the same as the probability of any other being counterfeit. But that two of the notes have exactly the same probability of being counterfeit is a measure zero event. It isn't happening. So Frankie Lee shouldn't be indifferent between the notes.

Of course, if the notes look exactly the same, then the probability that each is counterfeit is exactly the same. But that's only because that probability is one. In that case Frankie Lee should run away as fast as possible. That's not the realistic case.

The realistic case is that the notes look a little different to each other in ever so many respects. (Including, one hopes, their serial numbers.) Some will be a little more faded, or a little more torn, or a little more smudged or crumpled, than the others. It is overwhelmingly likely that these fades, tears, smudges, spills etc are the result of the normal wear and tear on the currency - wear and tear that paper notes tend to wear on their face. But every imperfection in every note is some evidence, very very marginal evidence but still evidence, that the note is counterfeit. And since Frankie Lee's evidence, on any extant theory of evidence, includes visible things like the tears, smudges etc on the notes, they are pieces of evidence that affect the evidential expected utility of taking each note. So if Frankie Lee wants to maximise evidential expected utility, there is precisely one note he should take. Though it probably won't be obvious to him which one it is, so he should spend some time thinking about this.

This is intuitively the wrong result. (Though it is what happens in the song.) Frankie Lee should just make a choice more or less arbitrarily. Since expected utility theory does not say this, expected utility theory is wrong.

# Back to Earth {#backearth}

The Frankie Lee and Judas Priest case is weird. Who offers someone money, then asks them to pick which note to take? And intuitions about such weird cases cases are sometimes deprecated. Perhaps the contrivance doesn't reveal deep problems with a philosophical theory, but merely a quirk of our intuitions. I am not going to take a stand on any big questions about the epistemology of intuitions here. Rather, I'm going to note that cases with the same structure as the story of Frankie Lee and Judas Priest are incredibly common in the real world. Thinking about the real world examples can both show us how pressing the problems are, and eventually show us a way out of those problems.

So let's leave Frankie Lee for now, just above the potted plain, and think about a new character. We will call this one David, and he is buying a few groceries on the way home from work. In particular, he has to buy a can of chickpeas, a bottle of milk, and a carton of eggs. To make life easy, we'll assume each of these cost the same amount - $5.^[If that sounds implausible to you, make the can/bottle/carton a different size, or change the currency to some other dollars than the one you're instinctively using. But I think this examples works tolerably well when understand as involving, for example, East Carribean dollars.] None of these purchases is entirely risk free. Canned goods are pretty safe, but sometimes they go bad. Milk is normally removed from sale when it goes sour, but not always. And eggs can crack, either in transit or just on the shelf. In David's world, just like ours, each of these risks is greater than the one that came before.

David has a favorite brand of chickpeas, of milk, and of eggs. And he knows where in the store they are located. So his shopping is pretty easy. But it isn't completely straightforward. First he gets the chickpeas. And that's simple; he grabs the nearest can, and unless it is badly dented, or leaking, he puts in in his basket. Next he goes onto the milk. The milk bottles have sell-by dates printed in big letters on the front. And David checks that he isn't picking up one that is about to expire. His store has been known to have adjacent bottles of milk with sell-by dates 10 days apart, so it's worth checking. But as long as the date is far enough in the future, he takes it and moves on. Finally, he comes to the eggs. (Nothing so alike as eggs, he always thinks to himself.) Here he has to do a little more work. He takes the first carton, opens it to see there are no cracks on the top of the eggs, and, finding none, puts that in his basket too. He knows some of his friends do more than this; flipping the carton over to check for cracks underneath. But the one time he tried that, the eggs ended up on the floor. And he knows some of his friends do less; just picking up the carton by the underside, and only checking for cracks if the underside is sticky where the eggs have leaked. He thinks that makes sense too, but he is a little paranoid, and likes visual confirmation of what he's getting. All done, he heads to the checkout, pays his $15, and goes home.

The choice David faces when getting the chickpeas is like the choice Frankie Lee faces. He has to choose from among a bunch of very similar seeming options. In at least the chickpeas example, he should just pick arbitrarily. But for very similar reasons to Frankie Lee, expected utility theory won't say that.

The standard model of practical rationality that we use in philosophy is that of expected utility maximisation. But there are both theoretical and experimental reasons to think that this is not the right model for choices such as that faced by Frankie or David. Maximising expected utility is resource intensive, especially in contexts like a modern supermarket, and the returns on this resource expenditure are unimpressive. What people mostly do, and what they should do, is choose in a way that is sensitive to the costs of adopting one or other way.

There are two annoying terminological issues around here that I mostly want to set aside, but need to briefly address in order to forestall confusion. 

I'm going to assume maximising expected utility means taking the option with the highest expected utility given facts that are readily available. So if one simply doesn't process a relevant but observationally obvious fact, that can lead to an irrational choice. I might alternatively have said that the choice was rational (given the facts the chooser was aware of), but the observational process was irrational. But I suspect that terminology would just add needless complication. 

I'm going to spend more time on another point that is partially terminological, but primarily substantive. That's whether we should identify the choice consequentialists recommend in virtue of the fact that it maximises expected utility with one of the options (in the ordinary sense of option), or something antecedent. I'm going to stipulate (more or less) that it is consistent with consequentialism that the choice can be something antecedent - it can be something like a choice procedure. And I'm going to argue that this is what the rational consequentialist should choose.

I'm going to call any search procedure that is sensitive to resource considerations a satisficing procedure. This isn't an uncommon usage. Charles @Manski2017 uses the term this way, and notes that it has rarely been defined more precisely than that. But it isn't the only way that it is used. Mauro @Papi2013 uses the term to exclusively mean that the chooser has a 'reservation level', and they choose the first option that crosses it. This kind of meaning will be something that becomes important again in a bit. And Chris @Tucker2016, following a long tradition in philosophy of religion, uses it to mean any choice procedure that does not optimize. Elena Reutskaja et al [-@Reutskaja2011] contrast a 'hybrid' model that is sensitive to resource constraints with a 'satisficing' model that has a fixed reservation level. They end up offering reasons to think ordinary people do (and perhaps should) adopt this hybrid model. So though they don't call this a satisficing approach, it just is a version of what Manski calls satisficing. Andrew Caplin et al (-@Caplin2011), on the other hand, describe a very similar model to Reutskaja et al's hybrid model - one where agents try to find something above a reservation level but the reservation level is sensitive to search costs - as a form of satisficing. So the terminology around here is a mess. I propose to use Manski's terminology: agents satisfice if they choose in a way that is sensitive to resource constraints. 

Ideally they would maximise, subject to constraints, but saying just what this comes to runs into regress problems [@Savage1967]. Let's set aside this theoretical point for a little, because it will be a bit deal in a little while, and go back to David and the chickpeas.

When David is facing the shelf of chickpeas, he can rationally take any one of them - apart perhaps from ones that are seriously damaged. How can expected utility theory capture that fact? I think if it identifies David's choices with the cans on the shelf, and not with a procedure for choosing cans, then it cannot.

It says that more than one choice is permissible only if the choices are equal in expected utility. So the different cans are equal in expected utility. But on reflection, this is an implausible claim. Some of the cans are ever so slightly easier to reach. Some of the cans will have ever so slight damage - a tiny dint here, a small tear in the label there - that just might indicate a more serious flaw. Of course, these small damages are almost always irrelevant, but as long as the probability that they indicate damage is positive, it breaks the equality of the expected utility of the cans. Even if there is no visible damage, some of the labels will be ever so slightly more faded, which indicates that the cans are older, which ever so slightly increases the probability that the goods will go bad before David gets to use them. Of course in reality this won't matter more than one time in a million, but one in a million chances matter if you are asking whether two expected utilities are strictly equal.

The common thread to the last paragraph is that these objects on the shelves are almost duplicates, but the most careful quality control doesn't produce consumer goods that are actual duplicates. There are always some differences. It is unlikely that these differences make precisely zero difference to the expected utility of each choice. And even if they do, discovering that is hard work.

So it seems likely that, according to the expected utility model, it isn't true that David could permissibly take any can of chickpeas that is easily reachable and not obviously flawed. Even if that is true, it is extremely unlikely that David could know it to be true. But one thing we know about situations like David's is that any one of the (easily reached, not clearly flawed) cans can be permissibly chosen, and David can easily know that. So the expected utility model, as I've so far described it, is false.

# You'll Never Be Satisfied (If You Try to Maximise) {#satisfied}

In all but a vanishingly small class of cases, the different cans will not have the same expected utility. But figuring out which can has the highest expected utility is a going to be work. It's possible in principle, I suppose, that someone could be skilled at it, in the sense that they could instinctively pick out the can whose shape, label fading, etc., reveal it to have the highest expected utility. Such a skill seems likely to be rare - though I'll come back to this point below when considering some other skills that are probably less rare. For most people, maximising expected utility will not be something that can be done through skill alone; it will take effort. And this effort will be costly, and almost certainly not worth it. Although one of the cans will be ever so fractionally higher in expected utility than the others, the cost of finding out which can this is will be greater than the difference in expected utility of the cans. So aiming to maximise expected utility will have the perverse effect of reducing one's overall utility, in a predictable way.

The costs of trying to maximise expected utility go beyond the costs of engaging in search and computation. There is evidence that people who employ maximising strategies in consumer search end up worse off than those who don't. @SchwartzEtAl2002 reported that consumers could be divided in 'satisficers' and 'maximizers'. And once this division is made, it turns out that the maximizers are less happy with individual choices, and with their life in general. This finding has been extended to work on career choice (@IyengarEtAl2006), where the maximisers end up with higher salaries but less job satisfaction, and to friend choice (@NewmanEtAl2018), where again the maximizers seem to end up less satisfied.

There is evidence here that maximizing is bad at what it sets out to achieve. But there are both empirical and theoretical reasons to be cautious about accepting these results at face value. Whether maximizers are worse off seems to be tied up to the 'paradox of choice' (@Schwartz2004), the idea that sometimes giving people even more choices makes them less happy with their outcome, because they are more prone to regret. But it is unclear whether such a paradox exists. One meta-analysis (@ScheibehenneEtAl2010) did not show the effect existing at all, though a later meta-analysis finds a significant mediated effect (@ChernevEtAl2015). But it could also be that the result is a feature of an idiosyncratic way of carving up the maximizers from the satisficers. Another way of dividing them up produces no effect at all (@DiabEtAl2008).

The theoretical reasons relate to Newcomb's problem. Even if we knew that maximizers were less satisfied with how things are going than satisficers, it isn't obvious that any one person would be better off switching. They might be like a two-boxer who would get nothing if they took one-box. There is a little evidence in @IyengarEtAl2006 that this isn't quite what is happening, but the overall situation is unclear.

The upshot of all this, I think, is that there are potentially two kinds of cost of engaging in certain kind of search and choice procedures. Some procedures are more costly to implement than others: they take more time, or more energy, or even more money. But further, some procedures might have a hedonic cost that extends beyond the time that the procedure is implemented. There is no theoretical or empirical guarantee that choosing widget W by procedure P1 will produce the same amount of happiness as choosing widget W by procedure P2. And especially for choices that are intended to produce happiness, this kind of factor should matter as well. In short, there are many more ways to assess a consumer choice procedure than the quality of the products in ends up choosing. And whether a choice procedure is rational is sensitive to all these things.

# Deliberation Costs and Infinite Regresses {#deliberationcosts}

The picture I've been building towards in the last section is not a new one. As I mentioned, the experimental work in [-@Reutskaja2011] suggests this is how people do reason. But the idea that people should reason this way goes back much further. It is often traced back to a footnote of Frank Knight's. Here is the text that provides the context for the note.

> Let us take Marshall's example of a boy gathering and eating berries ... We can hardly suppose that the boy goes through such mental operations as drawing curves or making estimates of utility and disutility scales. What he does, in so far as he deliberates between the alternatives at all*, is to consider together with reference to successive amounts of his "commodity," the utility of each increment against its "cost in effort," and evaluate the net result as either positive or negative (@Knight1921 66-7)

And the footnote attached to 'at all' says this

> Which, to be sure, is not very far. Nor is this any criticism of the boy. Quite the contrary! It is evident that the rational thing to do is to be irrational, where deliberation and estimation cost more than they are worth. That this is very often true, and that men still oftener (perhaps) behave as if it were, does not vitiate economic reasoning to the extent that might be supposed. For these irrationalities (whether rational or irrational!) tend to offset each other. (@Knight1921 67fn1)

Knight doesn't really give an argument for the claim that these effects will offset. And as John @Conlisk1996 shows in his fantastic survey of the late 20th century literature on bounded rationality, it very often isn't true. Especially in game theoretic contexts, the thought that other players might think that "deliberation and estimation cost more than they are worth" can have striking consequences. But our aim here is not to think about economic theorising, but about the nature of rationality.

There is something paradoxical, almost incoherent, about Knight's formulation. If it is "rational to be irrational", then being "irrational" can't really be irrational. There are two natural ways to get out of this paradox. One, loosely following David @Christensen2007, would be to say that "Murphy's Law" applies here. Whatever one does will be irrational in some sense. But still some actions are less irrational than others, and the least irrational will be to decline to engage in deliberation that costs more than it is worth. I suspect what Knight had in mind though was something different (if not obviously better). He is using 'rational' as more or less a rigid designator of the the property of choosing as a Marshallian maximiser does. And what he means here is that the disposition to not choose in that way will be, in the long run, the disposition with maximal returns.

This latter idea is what motivates the thought that rational agents will take what Conlisk calls "deliberation costs" into account. And Conlisk thinks that this is what rational agents will do. But he also raises a problem for this view, and indeed offers one of the clearest (and most widely cited) statements of this problem.

> However, we quickly collide with a perplexing obstacle. Suppose that we first formulate a decision problem as a conventional optimization based on the assumption of unbounded rationality and thus on the assumption of zero deliberation cost. Suppose we then recognize that deliberation cost is positive; so we fold this further cost into the original problem. The difficulty is that the augmented optimization problem will itself be costly to analyze; and this new deliberation cost will be neglected. We can then formulate a third problem which includes the cost of solving the second, and then a fourth problem, and so on. We quickly find ourselves in an infinite and seemingly intractable regress. In rough notation, let $P$ denote the initial problem, and let $F(.)$ denote the operation of folding deliberation cost into a problem. Then the regress of problems is $P, F(P), F^2(P), \ldots$ (@Conlisk1996 687)

Conlisk's own solution to this problem is not particularly satisfying. He notes that once we get to $F^3$ and $F^4$, the problems are 'overly convoluted' and seem to be safely ignored. This isn't enough for two reasons. First, even a problem that is convoluted to state can have serious consequences when we think about solving it. (What would _Econometrica_ publish if this weren't true?) Second, as is often noted, $F^2(P)$ might be a harder problem to solve than $P$, so simply stopping the regress there and treating the rational agent as solving this problem seems to be an unmotivated choice.

As Conlisk notes, this problem has a long history, and is often used to dismiss the idea that folding deliberation costs into our model of the optimising agent is a good idea. I use 'dismiss' advisedly here. As he also notes, there is very little _discussion_ of this infinite regress problem in the literature before 1996. The same remains true after 1996. What is done is that instead people appeal to the regress in a sentence or two to set aside approaches that incorporate deliberation cost in the way that Conlisk suggests.

Up to around the time of Conlisk's article, the infinite regress problem was often appealed to by people arguing that we should, in effect, ignore deliberation costs. After his article, the appeals to the regress comes from a different direction. It is usually from theorists arguing that deliberation costs are real, but the regress means it will be impossible to consistently incorporate them into a model of an optimizing agent. So we should instead rely on experimental techniques to see how people actually handle deliberation costs; the theory of optimization has reached its limit. This kind of move is found in writers as diverse as @GigerenzerSelton2001, @Odell2002, @Pingle2006, @ManganEtAl2010, @OgakiTanaka2017 and @Chakravarti2017. And proponents of taking deliberation costs seriously within broadly optimizing approaches, like Miles @Kimball2015, say that solving the regress problem is the biggest barrier to having such an approach taken seriously by economists. Like Kimball, I would like to solve this problem directly.

Here's how I plan to solve the regress problem. The solution is quite simple - almost blunt. What's going to be philosophically distinctive is the defence of it. 

What matters for optimality is that the thinker is following the procedure that is the optimal solution to $F(P)$. It doesn't matter that they compute that it is the optimal solution, or even that they are following it because it is the optimal solution. Because there is this external, success oriented condition, there isn't any extra problem that arises by 'folding in' computational costs. In the terminology from Conlisk, $F^n(P) = F(P)$, for all $n > 0$.

The solution to the regress problem is easy to state, but a little harder to motivate. There are two big questions to answer before we can say it is really motivated.

1. Why should we allow this kind of unreflective rule-following in our solution to the regress?
2. Why should we think that $F(P)$ is the point where this consideration kicks in, as opposed to $P$, or anything else?

There are a few ways to answer 1. One motivation traces back to the work by the artificial intelligence researcher Stuart @Russell1997. (Although really it starts with the philosophers Russell cites as inspiration, such as @Cherniak1986 and @Harman1973.) He stresses that we should think about the problem from the outside, as it were, not from inside the agent's perspective. How would we program a machine that we knew would have to face the world with various limitations? We will give it rules to follow, but we won't necessarily give it the desire (or even the capacity) to follow those rules self-consciously. That might be useful some of the time - though really what's more useful is knowing the limitations of the rules. And that can be done without following the rules as such. It just requires good dispositions to complicate the rules one is following in cases where such complication will be justified.

Another motivation is right there in the quote from Knight that set this literature going. Most writers quote the footnote, where Knight suggests it might be rational to be irrational. But look back at what he's saying in the text. The point is that it can be perfectly rational to use considerations other than drawing curves and making utility scales. What one has to do is follow internal rules that (non-accidentally) track what one would do if one was a self-consciously perfect Marshallian agent. That's what I'm saying too, though I'm saying it one level up.

Finally, there is the simple point that on pain of regress any set of rules whatsoever must say that there are some rules that are simply followed. This is one of the less controversial conclusions of the debates about rule-following that were started by @Wittgenstein1953. That we must at some stage simply follow rules, not follow them in virtue of following another rule, say the rule to compute how to follow the first rule and act accordingly, is an inevitable consequence of thinking that finite creatures can be rule followers. 

So question 1 is not really a big problem. But question 2 is more serious. Why $F(P)$, and why not something else? The short answer will be that any reason to think that rational actors maximize _expected_ utility, as opposed to actual utility, will also be a reason to think that they solve $F(P)$ and not $P$. The longer answer is a bit more roundabout, but it helps us to see what a solution to $F(P)$ will look like.

Start by stepping back and thinking about why we cared about _expected_ utility in the first place. Why not just say that the best thing to do is to produce the best outcome, and be done with it? Well, we don't say that because we take it as a fixed point of our inquiry that agents are informationally limited, and that the best thing to do is what is best given that limitation. Given some plausible assumptions, the best thing for the informationally limited agent to do would be to maximise expected utility. This is a second-best option, but the best is unavailable given the limitations that we are treating as unavoidable.

But agents are not just informationally limited, they are computationally limited too. And we could treat that as the core limitation to be modelled. As Conlisk says, it is "entertaining to imagine" theorists who worked in just this way [@Conlisk1996 691]. Let's imagine that when we meet the Martian economists, that's how they reason. Conlisk notes a few things that the Martian economists might do. They might disparage their colleagues who take informational limitations seriously as introducing ad hoc stipulations into theory. They might argue that informational limitations are bound to cancel out, or be eliminated by competition. They might argue that apparent informational limitations are really just computational ones, or at least can be modelled as computational ones. And so on.

What he doesn't add is that they might suggest that there is a regress worry for any attempt to add informational constraints. Let $Q$ be the initial problem as the Martians see it. That is, $Q$ is the problem of finding the best outcome given full knowledge of the situation, but the actual computational limitations of the agent. Then we suggest that we should also account for the informational limitations. Let's see if this will work, they say. Let $I$ be the function that transforms a problem into one that is sensitive to the informational limitations of the agent. But if we're really sensitive to informational limitations, we should note that $I(Q)$ is also a problem the agent has to solve under conditions of less than full information.^[At this point the Martians might note that while they are grateful that @Williamson2000 has highlighted problems with the KK principle, and these problems show some of the reasons for wanting to idealise away from informational limitations, they aren't in fact relying on Williamson's work. All they need is that agents do not exactly what they know. And that will be true as long as the correct epistemic logic is weaker than S5. And that will be true as long as someone somewhere has a false belief. And it would just be weird, they think, to care about informational limitations but want to idealise away from the existence of false beliefs.] So the informationally challenged agent will have to solve not just $I(Q)$, but $I^2(Q)$, and $I^3(Q)$ and so on.^[At this point, some of the Martians note that the existence of @Elster1979 restored their faith in humanity.]

Orthodox defenders of (human versions of) rational choice theory have to think this is a bad argument. And I think most of them will agree with roughly the solution I'm adopting. The right problem to solve is $I(Q)$, on a model where $Q$ is in fact the problem of choosing the objectively best option. If one doesn't know precisely what one's knowledge is, then one has to maximise expected utility somewhat speculatively. But that doesn't mean that one shouldn't maximise expected utility.

But the bigger thing to say is that neither we nor the Martians really started with the right original problem. The original problem, $O$, is the problem of choosing the objectively best option. The humans start by considering the problem $I(O)$, i.e., $P$, and then debate whether we should stick with that problem, or move to $F(I(O))$. The Martians start by considering the problem $F(O)$, i.e., $Q$, then debate whether we should stick with that or move to $I(F(O))$. And the answer in both cases is that we should move. 

Given the plausible commutativity principle, that introducing two limitations to theorising has the same effect whichever order we introduce them, $I(F(O)) = F(I(O)$$. That is, $F(P) = I(Q)$. And that's the problem that we should think the rational agent is solving.

But why solve that, rather than something more or less close to $O$? Well, think about what we say about an agent in a Jackson case who tries to solve $O$ not $I(O)$. (A Jackson case, in this sense, is a case where the choice with highest expected value is known to not have the highest objective value. So trying to get the highest objective value will mean definitely not maximising expected value.) We think it will be sheer luck if they succeed. We think in the long run they will almost certainly do worse than if they tried to solve $I(O)$. And in the rare case where they do better, we think it isn't a credit to them, but to their luck. In cases where the well-being of others is involved, we think aiming for the solution to $O$ involves needless, and often immoral, risk-taking.

The Martains can quite rightly say the same things about why $F(O)$ is a more theoretically interesting problem than $O$. Assume we are in a situation where $F(O)$ is known to differ from $O$. For example, imagine the decision maker will get a reward if they announce the correct answer to whether a particular sentence is a truth-functional tautology, and they are allowed to pay a small fee to use a computer that can decide whether any given sentence is a tautology. The solution to $O$ is to announce the correct answer, whatever it is. The solution to $F(O)$ is to pay to use the computer. And the Martians might point out that in the long run, solving $F(O)$ will yield better results. That if the agent does solve problems like $O$ correctly, even in the long run, this will just mean they were lucky not rational. That if the reward is that a third party does not suffer, then it is immorally reckless to not solve $F(O)$, i.e., to not consult the computer. And in general, whatever we can say that motivated "Rational Choice Theory", as opposed to "Choose the Best Choice Theory", they can say too.

Both the human and the Martian arguments look good to me. We should add in both computational and informational limitations into our model of the ideal agent. But note something else that comes from thinking about these Jackson cases. In solving a limitation sensitive problem, we aren't trying to approximate a solution to the limination insensitive problem. This is part of why the regress can stop here. To solve $F(X)$, we don't have to solve $X$, and then see how close the various computationally feasible solutions get to this solution. That's true in general because of Jackson cases, but it's especially true when $X$ is itself a complex problem. In trying to solve $F(I(O))$, i.e., $I(F(O))$, we aren't trying to maximise expected value, and then approximate that solution given computational limitations. Nor are we trying to be optimal by Martian standards (i.e., solve $F(O)$), then approximate that given informational limitations. We're just trying to get as good an outcome as we can, given our limitations. Doing that does not require solving any iterated problem about how well we can solve $F(I(O))$ given various limitations, any more than rationally picking berries requires drawing Marshallian curves.

So that's the solution to the regress. It is legitimate to think that there is a rule that rational creatures follow immediately, on pain of thinking that all theories of rationality imply regresses. And thinking about the contingency of how Rational Choice Theory got to be the way it is suggests that the solution to what Conlisk calls $F(P)$, or what I've called $F(I(O))$, will be that point.

What might that stopping point look like in practice? In his discussion of the regress, Miles @Kimball2015 suggests a few options. I want to focus on two of them.

> Least transgressive are models in which an agent sits down once in a long while to think very carefully about how carefully to think about decisions of a frequently encountered type. For example, it is not impossible that someone might spend one afternoon considering how much time to spend on each of many grocery-shopping trips in comparison shopping. In this type of modelling, the infrequent computations of how carefully to think about repeated types of decisions could be approximated as if there were no computational cost, even though the context of the problem implies that those computational costs are strictly positive. [@Kimball2015 174]

And that's obviously relevant to David in the supermarket. He could, in principle, spend one Saturday afternoon thinking about how carefully to check each of the items in the supermarket before putting it in his shopping cart. And then in future trips, he could just carry out this plan. This isn't terrible, but I don't think it's optimal. For one thing, there are much better things to do with Saturday afternoons. For another, it suggests we are back in the business of equating solving $F(P)$ with approximately solving $P$. And that's a mistake. Better to just say that David is rational if he just does the things that he would do were he to waste a Saturday afternoon this way, and then plan it out. And that thought leads to Kimball's more radical suggestion for how to avoid the regress,

> [M]odelling economic actors as doing constrained optimization in relation to a simpler economic model than the model treated as true in the analysis. This simpler economic model treated as true by the agent can be called a "folk theory" [@Kimball2015 175]

It's this last idea I plan to explore in more detail. (It has some similarities to the discussion of small worlds in @Joyce1999 70-77.) The short version is that David can, and should, have a little toy model of the supermarket in his head, and should optimize relative to that model. The model will be false, and David will know it is false. And that won't matter, as long as David treats the model the right way.

# Ignorance is Bliss {#ignorancebliss}

There are a lot of things that could have gone wrong with a can of chickpeas. They could have gone bad inside the can. They could have been contaminated, either deliberately or through carelessness. They could have been sitting around so long they have expired. All these things are, at least logically, possible.

But these possibilities, while serious, have two quite distinctive features. One is that they are very rare. In some cases they may have never happened. (I've never heard of someone deliberately contaminating canned chickpeas, though other grocery products like strawberries have been contamination targets.) The other is that there are few easy ways to tell whether they are actualised. You can scan each of the cans for an expiry date, but it is really uncommon that this is relevant, and it takes work since the expiry dates are normally written in such small type. If a can is really badly dented, I guess that weakens the metal and raises ever so slightly the prospect of unintentional contamination. But it's common to have shelves full of cans that have no dents, or at most very minor ones. 

Given these two facts - the rarity of the problems and the difficulty in getting evidence that significantly shifts the probability that this is one of the (rare) problems - the rational thing to do is choose in a way that is insensitive to whether those problems are actualised. Or, perhaps more cautiously, one should be vigilant, in the sense of @SperberEtAl2010, to some of these problems, and ignore the rest. But being vigilant about a problem means, I take it, being willing to consider it if and only if you get evidence that it is worth considering. In the short run, you still ignore the potential problem.

And to ignore a potential problem is to choose in a way that is insensitive to evidence for the problem. That makes sense for both the banknotes and the chickpeas, because engaging in a choice procedure that is sensitive to the probability of the problem will, in the long run, make you worse off.

In Kimball's terms, the rational shopper will have a toy model of the supermarket in which all cans of chickpeas that aren't obviously damaged are safe to eat. This will be a defeasible model, but on a typical grocery trip, it won't be defeated. In Joyce's terms, the small worlds the shopper uses in setting up the decision problem they face will all be ones in which the chickpeas are safe.

# Relate this to Knowledge

Say some stuff about how this gets me out of problems for my preferred theory of knowledge.


